// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventCheckInApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Conferência de Tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Workshop de Desenvolvimento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Feira de Startups"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hackathon Global"
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommunityId = 1,
                            Company = "Tech Corp",
                            FirstName = "João",
                            LastName = "Silva",
                            Title = "Desenvolvedor"
                        },
                        new
                        {
                            Id = 2,
                            CommunityId = 2,
                            Company = "DevHouse",
                            FirstName = "Maria",
                            LastName = "Souza",
                            Title = "Product Manager"
                        },
                        new
                        {
                            Id = 3,
                            CommunityId = 1,
                            Company = "InovaTech",
                            FirstName = "Carlos",
                            LastName = "Pereira",
                            Title = "CTO"
                        },
                        new
                        {
                            Id = 4,
                            CommunityId = 3,
                            Company = "WebSolutions",
                            FirstName = "Fernanda",
                            LastName = "Dias",
                            Title = "Designer"
                        },
                        new
                        {
                            Id = 5,
                            CommunityId = 4,
                            Company = "CloudX",
                            FirstName = "Lucas",
                            LastName = "Lima",
                            Title = "DevOps"
                        },
                        new
                        {
                            Id = 6,
                            CommunityId = 2,
                            Company = "AppFlow",
                            FirstName = "Ana",
                            LastName = "Costa",
                            Title = "QA Engineer"
                        },
                        new
                        {
                            Id = 7,
                            CommunityId = 1,
                            Company = "BitWise",
                            FirstName = "Rafael",
                            LastName = "Martins",
                            Title = "Engenheiro de Software"
                        },
                        new
                        {
                            Id = 8,
                            CommunityId = 3,
                            Company = "Tech Corp",
                            FirstName = "Juliana",
                            LastName = "Oliveira",
                            Title = "Scrum Master"
                        },
                        new
                        {
                            Id = 9,
                            CommunityId = 4,
                            Company = "WebSolutions",
                            FirstName = "Marcos",
                            LastName = "Ferreira",
                            Title = "Analista de Sistemas"
                        },
                        new
                        {
                            Id = 10,
                            CommunityId = 2,
                            Company = "DevHouse",
                            FirstName = "Camila",
                            LastName = "Rocha",
                            Title = "Tech Lead"
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.HasOne("Community", "Community")
                        .WithMany("People")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Community", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
